---
# tasks file for sbaerlocher.cifs

- name: "install cifs on RedHat"
  yum: name=cifs-utils state=present
  when: ansible_os_family == 'RedHat'

- name: "install cifs on Debian"
  apt: name=cifs-utils state=present
  when: ansible_os_family == 'Debian'

- name: "mount {{ item.name }} folder"
  mount: 
    state: "mounted" 
    fstype: "cifs"
    name: "{{ item.path }}"
    src: "{{ item.src }}"
    opts: "username={{ item.user }},password={{ item.password }},file_mode={{ item.file_mode }},dir_mode={{ item.dir_mode }}"
  with_items: "{{ samba_folder }}"
  when: samba_folder is defined