---
# tasks file for sbaerlocher.cifs

- name: "add OS specific task"
  include: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "defaults.yml"

- name: "mount {{ item.name }} folder"
  mount: 
    state: "mounted" 
    fstype: "cifs"
    name: "{{ item.path }}"
    src: "{{ item.src }}"
    opts: "username={{ item.user }},password={{ item.password }},file_mode={{ item.file_mode }},dir_mode={{ item.dir_mode }}"
  with_items: "{{ samba_folder }}"
  when: samba_folder is defined